INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AED', '784', '아랍에미리트 디르함', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AFN', '971', '아프가니스탄 아프가니', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ALL', '8', '알바니아 레크', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AMD', '51', '아르메니아 드람', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ANG', '532', '네덜란드령 안틸레스 휠던', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AOA', '973', '앙골라 콴자', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ARS', '32', '아르헨티나 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AUD', '36', '오스트레일리아 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AWG', '533', '아루바 플로린', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('AZN', '944', '아제르바이잔 마나트', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BAM', '977', '보스니아 헤르체고비나 태환 마르카', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BBD', '52', '바베이도스 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BDT', '50', '방글라데시 타카', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BGN', '975', '불가리아 레프', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BHD', '48', '바레인 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BIF', '108', '부룬디 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BMD', '60', '버뮤다 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BND', '96', '브루나이 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BOB', '68', '볼리비아 볼리비아노', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BOV', '984', 'Bolivian Mvdol (기금부호)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BRL', '986', '브라질 헤알', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BSD', '44', '바하마 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BTN', '64', '부탄 눌트럼', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BWP', '72', '보츠와나 풀라', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BYN', '933', '신 벨라루스 루블', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BYR', '974', '벨라루스 루블', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('BZD', '84', '벨리즈 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CAD', '124', '캐나다 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CDF', '976', '콩고 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CHE', '947', 'WIR 유로 (보완화폐)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CHF', '756', '스위스 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CHW', '948', 'WIR 프랑 (보완화폐)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CLF', '990', 'Unidad de Fomento (기금부호)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CLP', '152', '칠레 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CNY', '156', '중화인민공화국 위안', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('COP', '170', '콜롬비아 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('COU', '970', 'Unidad de Valor Real (UVR) (기금부호)[2]', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CRC', '188', '코스타리카 콜론', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CUC', '931', '쿠바 태환 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CUP', '192', '쿠바 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CVE', '132', '카보베르데 이스쿠두', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('CZK', '203', '체코 코루나', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('DJF', '262', '지부티 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('DKK', '208', '덴마크 크로네', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('DOP', '214', '도미니카 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('DZD', '12', '알제리 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('EGP', '818', '이집트 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ERN', '232', '에리트레아 낙파', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ETB', '230', '에티오피아 비르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('EUR', '978', '유로', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('FJD', '242', '피지 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('FKP', '238', '포클랜드 제도 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GBP', '826', '파운드 스털링', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GEL', '981', '조지아 라리', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GHS', '936', '가나 세디', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GIP', '292', '지브롤터 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GMD', '270', '감비아 달라시', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GNF', '324', '기니 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GTQ', '320', '과테말라 케찰', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('GYD', '328', '가이아나 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('HKD', '344', '홍콩 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('HNL', '340', '온두라스 렘피라', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('HRK', '191', '크로아티아 쿠나', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('HTG', '332', '아이티 구르드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('HUF', '348', '헝가리 포린트', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('IDR', '360', '인도네시아 루피아', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ILS', '376', '이스라엘 신 셰켈', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('INR', '356', '인도 루피', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('IQD', '368', '이라크 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('IRR', '364', '이란 리알', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ISK', '352', '아이슬란드 크로나', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('JMD', '388', '자메이카 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('JOD', '400', '요르단 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('JPY', '392', '일본 엔', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KES', '404', '케냐 실링', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KGS', '417', '키르기스스탄 솜', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KHR', '116', '캄보디아 리엘', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KMF', '174', '코모로 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KPW', '408', '조선민주주의인민공화국 원', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KRW', '410', '대한민국 원', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KWD', '414', '쿠웨이트 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KYD', '136', '케이맨 제도 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('KZT', '398', '카자흐스탄 텡게', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('LAK', '418', '라오스 킵', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('LBP', '422', '레바논 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('LKR', '144', '스리랑카 루피', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('LRD', '430', '라이베리아 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('LSL', '426', '레소토 로티', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('LYD', '434', '리비아 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MAD', '504', '모로코 디르함', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MDL', '498', '몰도바 레우', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MGA', '969', '마다가스카르 아리아리', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MKD', '807', '마케도니아 데나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MMK', '104', '미얀마 짯', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MNT', '496', '몽골 투그릭', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MOP', '446', '파타카', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MRO', '478', '모리타니 우기야', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MUR', '480', '모리셔스 루피', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MVR', '462', '몰디브 루피야', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MWK', '454', '말라위 콰차', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MXN', '484', '멕시코 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MXV', '979', 'Mexican Unidad de Inversion (UDI) (기금부호)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MYR', '458', '말레이시아 링깃', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('MZN', '943', '모잠비크 메티칼', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('NAD', '516', '나미비아 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('NGN', '566', '나이지리아 나이라', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('NIO', '558', '니카라과 코르도바', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('NOK', '578', '노르웨이 크로네', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('NPR', '524', '네팔 루피', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('NZD', '554', '뉴질랜드 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('OMR', '512', '오만 리알', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PAB', '590', '파나마 발보아', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PEN', '604', '페루 솔', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PGK', '598', '파푸아뉴기니 키나', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PHP', '608', '필리핀 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PKR', '586', '파키스탄 루피', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PLN', '985', '폴란드 즈워티', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('PYG', '600', '파라과이 과라니', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('QAR', '634', '카타르 리얄', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('RON', '946', '루마니아 레우', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('RSD', '941', '세르비아 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('RUB', '643', '러시아 루블', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('RWF', '646', '르완다 프랑', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SAR', '682', '사우디아라비아 리얄', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SBD', '90', '솔로몬 제도 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SCR', '690', '세이셸 루피', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SDG', '938', '수단 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SEK', '752', '스웨덴 크로나/크로노르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SGD', '702', '싱가포르 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SHP', '654', '세인트헬레나 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SLL', '694', '시에라리온 리온', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SOS', '706', '소말리아 실링', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SRD', '968', '수리남 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SSP', '728', '남수단 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('STD', '678', '상투메 프린시페 도브라', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SVC', '222', '엘살바도르 콜론', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SYP', '760', '시리아 파운드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('SZL', '748', '에스와티니 릴랑게니', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('THB', '764', '태국 밧', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TJS', '972', '타지키스탄 소모니', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TMT', '934', '투르크메니스탄 마나트', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TND', '788', '튀니지 디나르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TOP', '776', '통가 팡가', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TRY', '949', '터키 리라', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TTD', '780', '트리니다드 토바고 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TWD', '901', '신 타이완 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('TZS', '834', '탄자니아 실링', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('UAH', '980', '우크라이나 흐리우냐', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('UGX', '800', '우간다 실링', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('USD', '840', '미국 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('USN', '997', 'United States dollar (next day) (기금부호)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('UYI', '940', 'Uruguay peso en Unidades Indexadas (URUIURUI) (기금부호)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('UYU', '858', '우루과이 페소', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('UZS', '860', '우즈베키스탄 숨', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('VEF', '937', '베네수엘라 볼리바르', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('VND', '704', '베트남 동', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('VUV', '548', '바누아투 바투', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('WST', '882', '사모아 탈라', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XAF', '950', 'CFA 프랑 BEAC', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XAG', '961', '은 (1 트로이 온스)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XAU', '959', '금 (1 트로이 온스)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XBA', '955', 'European Composite Unit (EURCO) (채권 시장 단위)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XBB', '956', 'European Monetary Unit (E.M.U.-6) (채권 시장 단위)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XBC', '957', 'European Unit of Account 9 (E.U.A.-9) (채권 시장 단위)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XBD', '958', 'European Unit of Account 17 (E.U.A.-17) (채권 시장 단위)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XCD', '951', '동카리브 달러', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XDR', '960', '특별인출권', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XOF', '952', 'CFA 프랑 BCEAO', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XPD', '964', '팔라듐 (1 트로이 온스)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XPF', '953', 'CFP 프랑 (franc Pacifique)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XPT', '962', '백금 (1 트로이 온스)', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XSU', '994', 'SUCRE', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XTS', '963', 'Code reserved for testing purposes', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XUA', '965', 'ADB Unit of Account', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('XXX', '999', '통화 없음', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('YER', '886', '예멘 리알', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ZAR', '710', '남아프리카 공화국 랜드', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ZMW', '967', '잠비아 콰차', NOW());
INSERT INTO currency_code (currency_code, currency_number, currency_name, reg_datetime) VALUES ('ZWL', '932', '짐바브웨 달러 A/10', NOW());
